### ISSUE TITLE
Atreus TMK status

### ISSUE THREAD

**Issue by benswift** [technomancy/tmk_keyboard#11]
Hi Phil

Sorry about the Friday arvo flurry of issues.

I'm just interested in a status update on this TMK firmware - wondering how many
folks are using it? It seems like you've made noises on the mailing list that it's going to be the reccomended option in the future, but it's not ready for prime time?

Should new Atreus users be using this, or the [other firmware](https://github.com/technomancy/atreus-firmware)?

**Comment by BibleBelt** [comment]
Hi,

I used the other firmware briefly but switched quickly to this TMK based version.

I need german umlauts and use the neo layout (http://www.neo-layout.org/).I hit a roadblock somewhere. Of course I can't remember the exact problem now.

Phil recommended to switch to the TMK based firmware and this worked well.

The only drawback I encountered was that in my Windows environment resetting the keyboard using the reset key on the keyboard itself only put it into bootloader mode for a very short time. Uploaning a fresh firmware then became a game of luck. I switched to another computer that runs Linux natively and thinks worked flawlessly there.

**Comment by technomancy** [comment]
Hey, I'm sorry for the delay in the reply here; GitHub somehow unsubscribed me from this repo.

I would say the TMK firmware is likely going to be the way forward. I have been using it for a while on my own board, but there may be gaps in the documentation. If you want the simplest thing, it might be better to stick to the older one for the time being, but if you are up for trying something new and would like to help give feedback on TMK that would be welcome. TMK is definitely more featureful, which is nice.

**Comment by benswift** [comment]
Ok, no worries. I did get the TMK one up and running, but I'm back on
the old one since I wanted to try some header tweaks and loved the idea
of just changing the array in the header file to do that. But if I make
any progress with the TMK one I'll let you know.

**Comment by technomancy** [comment]
The TMK layout is now the officially-documented recommendation; the old atreus-firmware codebase is now recommended more for pedagogical purposes or lower-level hacking since it is easier to understand but less featureful.

**Comment by benswift** [comment]
Cool, yep, I moved over.  All good.
