### ISSUE TITLE
Missing % key in qwerty layout??

### ISSUE THREAD

**Issue by lorentrogers** [technomancy/tmk_keyboard#15]
Perhaps I'm just not seeing it, but where are the %, ~, |, and ^ keys? Although I do appreciate the addition of the arrow keys on L1, if we're missing basic characters, than this is a non-starter.

Also, in hunting around for them, I discovered that fn+shift prints 'q' -- is this a different issue?

**Comment by technomancy** [comment]
The %, ~, |, and ^ keys have to be moved in order to make room for the
arrows; you have to use shift-5, shift-6, etc. like you would on a
normal keyboard.

> Also, in hunting around for them, I discovered that fn+shift prints
> 'q' -- is this a different issue? 

This has been reported by someone else too, but I haven't been able to
repro. It might be a difference between the qwerty version and the
multidvorak version, but I hope to look into it soon. But I can see how
this would make the lack of a dedicated %, etc key much more problematic.

**Comment by lorentrogers** [comment]
Makes sense -- this was my first inclination, but the 'q' issue apparently got in the way. I'll try re-flashing the firmware and see if I can reliably reproduce it. 

As a side note, it may be worth mentioning how the shift key changes keys like this in the docs. I had the same learning-curve issue with ?, :, <, >.

**Comment by lorentrogers** [comment]
Ok. I just re-flashed the default qwerty firmware, and I think I may have some clues about what's going on here. Not sure how they could be solved, but at least they're clues.

I can reliably enter the symbols by pressing and holding the shift key first, then pressing Fn, then pressing the corresponding number key like you describe. This is definitely related to my capslock issue: #16 . 

When I follow this specific order, I enter capslock mode: 
- press shift
- press fn
- release shift
- release fn
- type a letter key

This always enters me into capslock. To get out of it, I can press and release the shift key.

I assume that this is not the intended interaction here? And, this probably needs documentation regardless.

**Comment by wolfish17** [comment]
I have encountered this. I think it is caused when the fn layer does not have the shift modifier mapped to the same key as the default layer. Therefore the release does not occur,   which seems logical and is sometimes convenient but sometimes irritating.

**Comment by technomancy** [comment]
Yeah, the q thing was a really stupid goof on my part. I had fn+shift mapped to fn4, and the function array only had 4 elements in it, so it was jumping off to a random place. I'm actually pretty surprised it didn't crash the whole firmware.

Anyway, 0701899 has the fix.

**Comment by technomancy** [comment]
I've also added a "qwerty_classic" which has the arrows back on L2 and has dedicated keys for %, ^, ~, and |.

**Comment by lorentrogers** [comment]
Thanks! I just flashed the update, and can confirm that all is well. Bug successfully squashed. 

I still think that the documentation could use some info on how the shift key works though. I'll probably put together a pull request for a draft of this.
