### ISSUE TITLE
Caps lock documentation?

### ISSUE THREAD

**Issue by lorentrogers** [technomancy/tmk_keyboard#16]
For some reason, I find that the qwerty layout randomly turns on capslock. I've not been able to figure out how I'm doing this, and I don't see it in the docs. I assume that the magic command is mapped to something, but I don't know what...

**Comment by technomancy** [comment]
I'm pretty sure this is due to shift being missing from the fn layer as discussed in #15, so it should be fixed in the latest version, but feel free to reopen if you still see it.

**Comment by lorentrogers** [comment]
Confirmed - this was a bug that has been fixed.
