### ISSUE TITLE
Printing 'e' instead of '.'

### ISSUE THREAD

**Issue by lorentrogers** [technomancy/tmk_keyboard#17]
Looks like something may be mapped wrong with the period key on layer 1. Pressing and holding Fn, then pressing the key directly to the right produces 'e'. According to the readme, this should be '.' instead.

Shift also produces a capital 'E' - just fyi. I'm using the default qwerty layout.

**Comment by technomancy** [comment]
Yep, another accidental holdover from the dvorak layout. Thanks for catching this.

**Comment by lorentrogers** [comment]
No problem -- thanks for fixing it!!

**Comment by lorentrogers** [comment]
Just flashed it and confirmed that it's fixed.
