### ISSUE TITLE
FN2 does not jump back to Layer0

### ISSUE THREAD

**Issue by Minsekt** [technomancy/tmk_keyboard#22]
Hello,

it jumps back to the momentary fn layer with numbers and punctuation and keeps it persistent until i press fn0 again.

im using a custom keymap but it also happens with the default qwerty keymap.

**Comment by technomancy** [comment]
Sorry; I can't reproduce the problem with the qwerty keymap. Can you
describe in more detail the steps and the results you're seeing and make
sure you're running the qwerty keymap from the latest revision? Perhaps
your custom keymap changed the fn_actions array. You might also try
doing a clean in between changing keymaps.

**Comment by Minsekt** [comment]
ive already edited the default qwerty keymap i was testing with, my fault. (it doesnt happne on the default keymaps) but i did found the problem too.

it looks like if FN2 is pressed it also presses the key on the layer below immediately too. on the default keymap thats FN0 obviously, so it jumps back to layer0. but i need FN0 to be on another key than FN2.

This also happened on the old atreus custom firmware(sending the key below FN2) with the exception that it actually jumped back to layer0 without pressing FN0 again.

ive added my keymap files so you can have a look at it.
my Layer2 doesnt make much sense propably, but thats a layer im using as a keypad for photshop and zbrush. it works fine, but its kinda annoying to press both keys to get back to layer0 as im saving every few minutes and have to enter a filename. 

so is FN2 working as intended? if it is, i have to come up with another layout the bottom row on layer0 i guess.




[Photoshop_Zbrush.zip](https://github.com/technomancy/tmk_keyboard/files/197067/Photoshop_Zbrush.zip)

**Comment by Minsekt** [comment]
so is it possible to separate the function keys or do they have to be the same key on every layer? if the error is on my side i just dig deeper, but just have some basic understanding of coding in general, ill get it done for my needs but if it isnt even possible i can have some peace because this is quite bugging me hehe

**Comment by technomancy** [comment]
Sorry for missing this earlier. For clarification, the key "under" a layer-switching key is always set to `KC_NO` in the default layouts to avoid this problem. I believe doing otherwise will cause unwanted key presses. Hope that helps.
