### ISSUE TITLE
Keys flipped horizontally on rev. 1 Atreus

### ISSUE THREAD

**Issue by aidalgol** [technomancy/tmk_keyboard#26]
On my first-revision Atreus, the keys are flipped horizontally with the TMK firmware.  There doesn't appear to be a single variable that can be flipped to fix this, so it looks as if we need to add support for this case in `matrix.c` that can be selected at compile-time with a `#define`.

**Comment by technomancy** [comment]
This should be handled by setting `OPT_DEFS=-DPCBDOWN` when compiling.

**Comment by aidalgol** [comment]
Well I feel silly now.  It was _right there_ in front of my face, in the readme. *facepalm*
