### ISSUE TITLE
Flipped columns required on a non-flipped keyboard?

### ISSUE THREAD

**Issue by lorentrogers** [technomancy/tmk_keyboard#29]
I know I've got an up-facing chip, and I used to `make install...` with no problem a few months ago. But now, after having re-installed Debian and all my build tools, it seems like I need to include the `OPT_DEFS=-DPCBDOWN` option when building. Any idea what may have changed in the past few months? (Or perhaps I'm just loosing it?)

**Comment by technomancy** [comment]
Sure; the assembly instructions have actually changed on this. The recommended approach is now to install with the controller exposed, which makes it easier to reach for repairs: https://github.com/technomancy/tmk_keyboard/commit/b6e2c476d757d70442052713912c6824f34681f7

**Comment by lorentrogers** [comment]
Thanks for clarifying -- glad I'm not loosing it!
