### ISSUE TITLE
Bidirectional Momentary L2?

### ISSUE THREAD

**Issue by dbordak** [technomancy/tmk_keyboard#3]
Momentary L2 is triggered by FN + Shift. Would it be possible to do it with Shift + FN, as well?

As it stands, I accidentally do that anyway most of the time.

**Comment by joefiorini** [comment]
I'm looking through the code in `keymap_qwerty_ml2.c` and I can't figure out how to determine the keypresses required for the various `fn_actions`. @dbordak how did you determine Shift + FN?

**Comment by c2lknt** [comment]
L2 triggering off of fn+shift is actually a L2 button being active on the shift key on the L1 - so you enter L1 by pressing FN, and enter L2 by pressing Shift.  

To make it bidirectional, you would set the L0 Shift to activate L1 and the L1 FN to activate L2 - I'm not sure that would actually work, but I'm just saying that to explain the logic and illustrate the following point: 

Doing this, you'd lose your L0 shift, and if you're willing to do that, you may as well put a L2 button on your L0.  (If you're on an Atreus, that's already built on the _2fn layouts.)

**Comment by technomancy** [comment]
Sorry for the delay on this response; Github somehow unsubscribed me to notifications.

So yeah, there is no straightforward way to do this unfortunately. You would have to replace shift with another layer key, which would have some unfortunate implications with tracking presses and releases.
