### ISSUE TITLE
Move mouse keys to left hand

### ISSUE THREAD

**Issue by lorentrogers** [technomancy/tmk_keyboard#30]
Since we've got the arrow keys on the left, I think it'll make more sense to have the mouse keys in the same place. I'm thinking the j, k, l keys would be left, center, and right click. 

I can put together a PR that demos it. Thoughts?

**Comment by technomancy** [comment]
Sure; this is just for `keymap_mouse.c`, right?

**Comment by lorentrogers** [comment]
Yeah, I just arranged it to match the directional arrow keys.
