### ISSUE TITLE
Warning if not root before upload

### ISSUE THREAD

**Issue by lorentrogers** [technomancy/tmk_keyboard#31]
I always forget that I need to `sudo` my `make upload` command. Perhaps we could put a warning in there that says something like "It looks like you're not root. You may not have privileges to upload to your keyboard, causing this to hang. Press Ctrl+C to cancel."

This would save me a couple of minutes hammering away at the keyboard waiting for it to enter programming mode and upload.

**Comment by technomancy** [comment]
It's best if you don't run the command as root; rather you should fix the permissions issue and allow your regular user to write to the device in question. Perhaps this needs to be made clearer in the documentation?

**Comment by lorentrogers** [comment]
Hmm - I didn't know that. Is it documented already somewhere? (A quick search through things didn't turn up anything.) May be worthwhile to check for permissions (and print a message if needed) before going into the AVR loop.

**Comment by technomancy** [comment]
Oh yes; it would be much better if we detected the "exists, but not readable by the current user" situation and warned of that. Not sure why I didn't think of that long ago.

**Comment by lorentrogers** [comment]
Cool. Is the permissions issue documented already?

**Comment by technomancy** [comment]
The docs mention making sure you have write permission, and how to add a udev rule if you are in Linux. If there's anything else you think would make it clearer I'm open to suggestions.

**Comment by lorentrogers** [comment]
Aha - I definitely read that part of the docs, but something didn't totally make sense about it. Now that we've had this conversation, I know to run the `make udev` command as root. But something about the way the readme was written didn't make that apparent. I'll see if I can clarify and send over a PR.

On a related note, couldn't we check the permissions in the `make upload` command? If they're not available for the current user, suggest running `make udev`?

**Comment by lorentrogers** [comment]
I added a line in #34 that may help folks like me.
