### ISSUE TITLE
Can't find the /dev tty for my atreus

### ISSUE THREAD

**Issue by arthurnn** [technomancy/tmk_keyboard#38]
```
$ ls /dev > /tmp/dev-off # run this while the device is unplugged
$ ls /dev > /tmp/dev-on # run this while the device is in bootloader mode
$ diff /tmp/dev-off /tmp/dev-on # this will show the device path
```

Won't give me any diff :(
Any other method to find out which usb is my atreus connected to?
i am on MacOS

**Comment by technomancy** [comment]
Can you confirm that the LED on the controller is pulsing to indicate it's in bootloader mode?

It will only stay in bootloader mode for a few seconds, so you need to run the second ls command before it exits.

**Comment by arthurnn** [comment]
@technomancy ❤️  thanks.
I thought i were suppose to plug it off, run, and plug in and run again.. Didn't know it needed to be on boot mode.
Got it now..
